Subject: =?utf-8?b?0J/RgNC40LLQtdGCINC40Lcg0LrQvtC90YHQvtC70Lg=?=
From: JTProg_ru <pupezhnik@gmail.com>
To: Kalandarov Yura <savin@argosy-tech.ru>
Content-Type: text/plain; charset="utf-8"
Content-Transfer-Encoding: base64
MIME-Version: 1.0

0J/RgNC40LLQtdGCINGC0LXQsdC1INC40Lcg0LzQvtC10Lkg0LrQvtC90YHQvtC70LghCtCg0LXRiA==
0LjQuyDRgtC10LHQtSDQvdCw0L/QuNGB0LDRgtGMINC/0L7RgtC+0LzRgyDRh9GC0L4g0LzQvdC1IA==
0YHRgtCw0LvQviDRgdC60YPRh9C90L4hCtCX0KvQliDQldGB0LvQuCDRgtGLINGN0YLQviDQv9GA0A==
vtGH0LjRgtCw0LssINGC0L4g0L3QsNC/0LjRiNC4INC80L3QtSDQsiDQotC10LvQtdCz0YDQsNC8IQ==
CgotLS0KSlRQcm9nX3J1Cg==
